spring.application.name=application-service
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/sigorta_db?currentSchema=application_schema
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


spring.liquibase.change-log=classpath:db/changelog/master.xml
